version: "{build}"

platform: x64

branches:
  only:
    - master

# Source Config
clone_folder: c:\gopath\src\github.com\ReconfigureIO\goblin

environment:
  GOPATH: c:\gopath
  GOVERSION: 1.7.1

init:
  - git config --global core.autocrlf input

install:
  # Install the specific Go version.
  - rmdir c:\go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.msi
  - msiexec /i go%GOVERSION%.windows-amd64.msi /q
  - set Path=c:\go\bin;c:\gopath\bin;C:\Program Files (x86)\Bazaar\
  - go version
  - go env

test_script:
  - go test github.com/ReconfigureIO/goblin

build_script:
  - go build github.com/ReconfigureIO/goblin/cmd/goblin -o c:\gopath\src\github.com\ReconfigureIO\goblin\build\goblin.exe

artifacts:
  - path: c:\gopath\src\github.com\ReconfigureIO\goblin\build\goblin.exe
